export const IPC_CHANNELS = {
  PRODUCT_SEARCH: 'product:search',
  PRODUCT_CANCEL_SEARCH: 'product:cancel-search',
  PRODUCT_COPY_ADOPT: 'product:copy-adopt',
  PRODUCT_SESSION_STATUS: 'product:session-status',
  PRODUCT_LOGIN: 'product:login',
  PRODUCT_LOGOUT: 'product:logout',
  PRODUCT_SESSION_CHANGED: 'product:session-changed',
  PRODUCT_ANNOUNCE_REFRESH: 'product:announce-refresh',
  PRODUCT_ANNOUNCE_INVALIDATED: 'product:announce-invalidated',
  PRODUCT_ESCALATE: 'product:escalate',
  PRODUCT_RECORD_TERMINAL: 'product:record-terminal',
  PRODUCT_INACCURACY_REPORT: 'product:inaccuracy-report',
  PRODUCT_CATALOG: 'product:catalog',
  PRODUCT_RETRIEVAL_PREFERENCE_GET: 'product:retrieval-preference-get',
  PRODUCT_RETRIEVAL_PREFERENCE_SET: 'product:retrieval-preference-set',
  COPY_TEXT: 'clipboard:copy-text',
  GET_WINDOW_CONTEXT: 'overlay:get-window-context',
  OPEN_SEARCH: 'overlay:open-search',
  OPEN_DASHBOARD: 'dashboard:open',
  DASHBOARD_WORDING_LIST: 'dashboard:wording-list',
  DASHBOARD_CONTENT_SESSION: 'dashboard:content-session',
  DASHBOARD_CONTENT_PARSE: 'dashboard:content-parse',
  DASHBOARD_CONTENT_IMPORT: 'dashboard:content-import',
  DASHBOARD_CONTENT_PUBLISH: 'dashboard:content-publish',
  DASHBOARD_ITERATION_LIST: 'dashboard:iteration-list',
  DASHBOARD_ITERATION_START: 'dashboard:iteration-start',
  DASHBOARD_ITERATION_CLOSE: 'dashboard:iteration-close',
  DASHBOARD_OPS_RETRIEVAL: 'dashboard:ops-retrieval',
  DASHBOARD_OPS_SOP_CATALOG: 'dashboard:ops-sop-catalog',
  DASHBOARD_OPS_SOP_IMPORT: 'dashboard:ops-sop-import',
  DASHBOARD_OPS_SOP_PATCH: 'dashboard:ops-sop-patch',
  DASHBOARD_OPS_SOP_DELETE: 'dashboard:ops-sop-delete',
  DASHBOARD_OPS_SCRIPT_PATCH: 'dashboard:ops-script-patch',
  DASHBOARD_OPS_SCRIPT_DELETE: 'dashboard:ops-script-delete',
  DASHBOARD_OPS_SOFTWARE: 'dashboard:ops-software',
  DISMISS: 'overlay:dismiss',
  REPORT_UI_PHASE: 'overlay:report-ui-phase',
  REPORT_HANDOFF_MILESTONE: 'overlay:report-handoff-milestone',
  REPORT_QUERY_LAYOUT: 'overlay:report-query-layout',
  RESIZE_QUERY_HEIGHT: 'overlay:resize-query-height',
  MOVE_FOX_BY: 'overlay:move-fox-by',
  COMMIT_FOX_DRAG_SETTLE: 'overlay:commit-fox-drag-settle',
  SET_FOX_PEEK: 'overlay:set-fox-peek',
  OVERLAY_COMMAND: 'overlay:command',
  LOGIN_WINDOW_CHOOSE_FEISHU: 'login-window:choose-feishu',
  LOGIN_WINDOW_SUBMIT_ACCOUNT: 'login-window:submit-account',
  LOGIN_WINDOW_CANCEL: 'login-window:cancel',
  SOP_WINDOW_OPEN: 'sop-window:open',
  SOP_WINDOW_ENTRY_AVAILABLE: 'sop-window:entry-available',
  SOP_WINDOW_RESUME_AVAILABLE: 'sop-window:resume-available',
  SOP_WINDOW_CLOSE: 'sop-window:close',
  SOP_WINDOW_END_FLOW: 'sop-window:end-flow',
  SOP_WINDOW_RESTART: 'sop-window:restart',
  SOP_WINDOW_CHOOSE_EDGE: 'sop-window:choose-edge',
  SOP_WINDOW_NEXT_STEP: 'sop-window:next-step',
  SOP_WINDOW_MOVE_BY: 'sop-window:move-by',
  SOP_WINDOW_REPORT_LAYOUT: 'sop-window:report-layout',
  SOP_WINDOW_COPY_CURRENT: 'sop-window:copy-current',
  SOP_WINDOW_PROJECTION: 'sop-window:projection',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const IPC_CHANNEL_WHITELIST: readonly IpcChannel[] = Object.freeze(
  Object.values(IPC_CHANNELS),
);
